name: "BCFV Test Suite"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  unit-tests:
    name: Run bcfv tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run bcfv test suite
        run: |
          cd "$GITHUB_WORKSPACE"
          bash ./tests/test_bcfv.sh
